title: Chris Ault
subtitle: Python, Docker, Linux, Bash, Make, AWS, GIT, Jupyter, Pandas, Selenium
description: >- # this means to ignore newlines until "baseurl:"
  Full Stack software engineer in Florida looking to relocate, specializing in Python and Virtualization using Docker.

url: "//chris-ault.rocks" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog
theme_color: ff7601

urls:
    - text: About
      url : /
    - text: Resume
      url : /resume
    - text: Recent Projects
      url: /projects
    - text: Gallery
      url: /gallery
    - text: Contact Me
      url : /contact


# Edit these details

author_logo: profile.jpg
author: Chris Ault
author_bio: Hi, my name is Christopher Ault, I'm a software engineer in Florida seeking dev-ops or full-stack positions nationwide.
author_email: "chris.ault@ieee.org"
author_location: Florida
author_website_url: "https://chris-ault.rocks"
typewrite-text: Chris Ault Loves writing quality, tested, consistent code.

author_work_experiences:
            - company_name: Minimal Metrics
              company_logo: mm_orange.png
              company_url:
              designation: Software Engineer - (10/2018 - 8/2020)
              description: Write and test features written in Python and Make using various ORM along with Docker Virtualization
              visibility: true
            - company_name: 
              company_logo: nwAdm.jpg
              company_url:
              designation: Network Administrator
              description: Configure multiple DD-WRT routers, switches, windows desktops
              visibility: true

author_education_details:
              - college_logo: uwf_seal.png
                college_name: University of West Florida
                college_url: https://uwf.edu/
                college_degree: Computer Science, Cyber Security - 2018
                description: Bachelors Degree
                visibility: true
              - college_logo: nwfsc.jpg
                college_name: Northwest Florida State College
                college_url: https://nwfsc.edu/
                college_degree: Associates in Arts - 2013
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
#twitter_username: johndoe
github_username:  chris-ault
#facebook_username: johndoe
linkedin_username: chris-ault
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: sp33dsk8@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 6
per_page: 6
paginate_path: "/projects/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
#collections:
# - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build.sh

destination: ./build
